pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                withMaven(maven: 'jenkins-maven', mavenSettingsConfig: '980f523f-81dc-4df2-8840-fb351ff6ce11') {
                    bat 'mvn clean package'
                }
            }
        }
    }
}
