pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                withMaven(maven: 'jenkins-maven', mavenSettingsConfig: 'global') {
                    bat 'mvn clean package'
                }
            }
        }
    }
}
