pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // Checkout the source code from the repository
                checkout scm

                // Build the project using Maven
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                // Run tests using Maven
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                // Deploy the application
                sh 'mvn spring-boot:run'
            }
        }
    }
}
