pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                dir('./gateway-service') {
                    withMaven(maven: 'Maven 3.9.2') {
                        bat 'mvn clean package'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                dir('./gateway-service') {
                    withMaven(maven: 'Maven 3.9.2') {
                        bat 'mvn test'
                    }
                }
            }
        }
        stage('Docker Build Image') {
            steps {
                dir('./gateway-service') {
                    script {
                        bat 'docker build -t gateway .'
                    }
                }
            }
        }
        stage('Docker Run') {
            steps {
                dir('./gateway-service') {
                    script {
                        bat 'docker stop gateway-container || true'
                        bat 'docker rm gateway-container || true'
                        bat 'docker run -d -p 9000:9000 --name gateway-container gateway'
                    }
                }
            }
        }
    }
}