pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                dir('./demo') {
                    withMaven(maven: 'Maven 3.9.2') {
                        bat 'mvn clean package'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                dir('./demo') {
                    withMaven(maven: 'Maven 3.9.2') {
                        bat 'mvn test'
                    }
                }
            }
        }
        stage('Docker Build and Run') {
            steps {
                script {
                    sh 'docker build -t payment-image .C:\\Users\\TECHCOM\\Desktop\\ISASH-ECommerce-Project\\demo'
                    sh 'docker run -d -p 7000:7000 --name payment-container payment-image'
                    }
                }
            }
        }
}
