pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                dir('./demo') {
                    withMaven(maven: 'Maven 3.9.2') {
                        bat 'mvn clean package'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                dir('./demo') {
                    withMaven(maven: 'Maven 3.9.2') {
                        bat 'mvn test'
                    }
                }
            }
        }
        stage('Docker Build Image') {
            steps {
                dir('./demo') {
                    script {
                        bat 'docker build -t payment .'
                    }
                }
            }
        }
        stage('Docker Run') {
            steps {
                dir('./demo') {
                    script {
                        bat 'docker stop payment-container || true'
                        bat 'docker rm payment-container || true'
                        bat 'docker run -d -p 7000:7000 --name payment-container payment'
                    }
                }
            }
        }
    }
}
