pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                dir('./demoDB') {
                    withMaven(maven: 'Maven 3.9.2') {
                        bat 'mvn clean package'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                dir('./demoDB') {
                    withMaven(maven: 'Maven 3.9.2') {
                        bat 'mvn test'
                    }
                }
            }
        }
        stage('Docker Build Image') {
            steps {
                dir('./demoDB') {
                    script {
                        bat 'docker build -t products_image .'
                    }
                }
            }
        }
        stage('Docker Run') {
            steps {
                dir('./demoDB') {
                    script {
                        bat 'docker stop springapplication-on-docker || true'
                        bat 'docker rm springapplication-on-docker || true'
                        bat 'docker run -d -p 8080:8080 --name springapplication-on-docker products_image'
                    }
                }
            }
        }
    }
}